```{python}
import numpy as np
import math
import matplotlib.pyplot as plt
import random
import timeit
import scipy.fftpack
import scipy.io as sio
from scipy import stats
from mpl_toolkits.mplot3d import Axes3D
from scipy import signal
from scipy import interpolate
from PIL import Image
```


## Rhythmicity in walking (gait)

Gait, the the waling cadence is quite rythmic, which makes it amenable to
Fourier analysis. In this use case we will compare the gait dynamics of Parkinson patients (pd1-si.txt) and healthy control individuals (y1-23.si.txt), both from [physiobank](https://physionet.org/physiobank/database/gaitdb/). `gait.mat` contains two datasets, both with two columns and 222 rows. One corresponds to Parkinson's disease patients (COLOR) and another for healthy matched controls, people with similar age, education, lifestyle, etc. but without the disease (COLOR). We plot our data so the first column is on the x axis, representing the time. The second is represented on the y axis shows the stride time in seconds (delay between one step and the next). Just by comparing the lines is possible to see the Parkinson's patient gait is slower (higher stride time) and more variable than it is for control.

FT is not directly applicable for this data, as it is not regularly space, thus, it will need to be transformed before we contine. For that, we create a new array with a regular sampling where the step timestamps are ones and the rest of observations are zeroes.  

```{python}
# Load the data. If you get an error on this line,
# make sure your Python session is in the same directory as the data.
# SOURCES:
#  Data downloaded from https://physionet.org/physiobank/database/gaitdb/
#   Parkinson's patient data is pd1-si.txt
#   Young control data is y1-23.si.txt
matdata = sio.loadmat('FourierMXC_09_apps/gait.mat')

# extract data from mat file
park = matdata['park']
cont = matdata['cont']

srate  = 1000

def to_regular(dataset, srate):

    # Duration in time slices
    times = dataset[:, 0]
    duration = times[-1]
    slice_count = int(np.ceil(duration * srate)) + 1
    
    # create time series of steps
    step_idx = (times * srate).astype(int)
    is_step = np.zeros(slice_count)
    is_step[step_idx] = 1

    # time vector and number of time points
    times = np.arange(0, slice_count)/srate

    return times, is_step
    
parktx, parkts = to_regular(park, srate)
conttx, contts = to_regular(cont, srate)

# plot the time course of steps
stride_canvas, stride_panels = plt.subplots(2, 1, sharex=True)
stride_panels[0].plot(park[:,0],park[:,1],label="Parkinson patient")
stride_panels[0].plot(cont[:,0],cont[:,1],label="Control")
stride_panels[0].set_ylabel("Stride time (s)")
stride_panels[0].legend(ncols=2)

stride_panels[1].plot(conttx, contts) # should be 
stride_panels[1].plot(parktx,parkts) # stemplot rendering was too slow
stride_panels[1].set_ylim(0)
stride_panels[1].set_ylabel("Had stride")
stride_panels[1].set_xlim([0,75])
stride_panels[1].set_xlabel("Time (sec.)");
``` 

When we plot the power spectrum we see there are amplitude spikes. The first
peak is the dominant walking frequency, slightly under one step per second
(1 Hz, a bit lower for the Parkinson's patient).The peaks are called
"harmonics", and are are artifacts of rhythmic but non-sinusoidal time series.
This is induced by the binarization, which makes necessary non-zero energy at
higher harmonics, or higher frequencies, in order to represent the sharp edges.
(SEE SECTION ON NON STATIONARITIES).

```{python}
#% define sampling rate
def to_freq(dataset, srate):
    length = len(dataset)
    nyquist_idx = int(np.floor(length/2) + 1)
    freq = np.linspace(0, srate/2, nyquist_idx)
    power = 2 * np.abs(scipy.fftpack.fft(dataset)/length)
    return freq[1:], power[1:len(freq)]

plt.plot(*to_freq(parkts, srate=srate), label="Parkinson patient")
plt.plot(*to_freq(contts, srate=srate), label="Control")
plt.legend(ncols=2)
plt.ylim(0, 1e-3)
plt.xlim([0,7])
```

If we interpret the data, we see that both the fundamental frequency and all
the harmonics are wider in the Parkinson's patients compared to the control
patients. This is the spectral manifestation of this increase in variability
that you see in this plot, which indicates that there is greater signal
non-stationary for the patient compared to the control. These kinds of analyses
can be used to assess disease severity and to track symptom improvement
with medication in Parkinson's disease patients and other motor diseases.

## Rhythmicity in brain waves

This example shows an electroencephalogram (EEG), a record of electrical brain activity taken while the individual was sitting quietly in a dark room. It is
well known that the brain exhibits rhythmicity at multiple time scales. But
during rest most prominent brain activity pattern has a frequency of 10 Hz.
This was discovered almost 100 years ago by Hans Berger, who called it the
"alpha" rhythm, the first letter of the Greek alphabet, as it was the most
prominent feature of the data that he saw.

`EEGrestingState.mat` contains a variable called `EEGdata`, which is a one by
122.880 time points and a second variable called `srate`, depicting the
sampling rate (1024 Hz). To plot the data in the time domain we will create an
arbitrary time vector going from 0 to just under the number of time points,
which is divided by the sampling rate. When we visualize it we see it is 2
minutes long (120 s.). The initial impression from visualizing the full time
series, is that is noisy, but it is only because brain dynamics are faster than
what you can be distinguished at that scale. If we zoom to a smaller time scale, there are a lot of interesting dynamics that are happening at a smaller time
scale. On the period 43-45 we can see the alpha rythm relatively well, but it
does show differently along the recording.

```{python}

matdata = sio.loadmat('FourierMXC_09_apps/EEGrestingState.mat')

# extract data from mat file
eegdata = matdata['eegdata'].flatten()
srate   = matdata['srate'].item()


n = len(eegdata)
timevec = np.arange(n)/srate

start = int(43 * srate)
end = int(45 * srate)

plt.plot(timevec[start:end], eegdata[start:end])
plt.xlabel('Time (sec.)')
plt.ylabel('Amplitude (muV)')
plt.title('Time domain signal')
plt.xlim(43, 45)
```

Here we plot the amplitude spectrum with and without smoothing (black and gray,
respectively), mostly to dampen the effect of the non-stationarities and make
it easier to interpret. There are 3 note-worthy features on this spectrum: the
narrow peak here at 50 hertz is an artifact caused by electrical line noise.
It is very narrow in frequency (moreso in the unfiltered spectrum), so we can
safely ignore it.

The second relevant feature the decrease of power as frequeny increases. This
trend called "one over f" (1/f), a common spectral feature present in many
biological and physical systems. ~~People have speculated that this reflects a scale-free or a fractal-like organization in nature and in this case, in functional brain organization.~~

~~Or you could say the other way around: as frequencies get higher, the power is decreasing. Now, you have to ignore this little bit here. I've detrended this time series, so that actually removes the DC component, the zero hertz component.~~

Finally, there is a robust peak in the power spectrum at around 10 hertz: the
alpha rhythm. It is surprisingly wider compared with artifact we mentioned
before. This happens because the electrical line noise at 50 Hz is very
stationary, whereas the peak of alpha is broad because it is a non-stationary
feature in the data, as brain activity reflects temporal dynamics in
perception, thought and consciousness.

```{python}
hz, ampspect = to_freq(eegdata, srate)
filtered = scipy.signal.savgol_filter(ampspect, window_length=50, polyorder=1)

# show amplitude spectrum
plt.plot(hz, ampspect, color="gray", lw=.25)
plt.plot(hz, filtered, c="k", lw=1)
plt.xlim([0,70])
plt.ylim([0,.6])
plt.title('Frequency domain')
plt.show()
```


## Convolution theorem

Convolution is an operation in which two input signals are combined to produce
an output signal containing features from the the inputs. One of the inputs is
called "signal", whereas the other is called "kernel". The convolved result is
longer than either inputs, but the extra parts at either side will be cut off
in the end.

The procedure for implementing convolution in the time domain is to flip the
kernel and slide it through the signal, computing the dot product between one
and the other at each time step. Convolution can also be implemented in the
frequency domain thanks to the convolution theorem, which states that
convolution in the time domain is equivalent to multiplication in the frequency
domain. Thus, we can apply the FT to the signal and multiply them element-wise
(frequency-wise), and then apply the inverse FT to bring the convolved
to the time domain.

~~This turns out to be a much faster and much more elegant implementation of convolution compared to a sliding time series of dot products.~~

### Python

Over the first block we define define the signal and the kernel. Within
`convolve_over` we apply the FFT over both the signal and the kernel, which
are multiplied element-wise to obtain the convolution between these spectra.
The result is brought to the time tdomain using the inverse FFT, and trimmed
to match the length of the original signal. The last block just plots the
signal, the kernel, and the convolved result obtained with our implementation
and with Numpy.

```{python}

# Make the signal and the kernel

m = 50 # length of signal
n = 11 # length of kernel

signal = np.zeros(m)
signal[int(m*.4):int(m*.6)] = 1

kernel = np.zeros(n)
kernel[int(n*.25):int(n*.8)] = np.linspace(1,0,int(n*.55))

# Apply the convolution
def convolve_over(kernel, signal):
    result_length = (len(kernel) + len(signal)) - 1
    trim_length = int(len(kernel)//2)
    product = np.multiply(
        scipy.fftpack.fft(signal, result_length),
        scipy.fftpack.fft(kernel, result_length)
    )
    convolved = np.real(scipy.fftpack.ifft(product))
    return convolved[trim_length:-trim_length]


my_convolve = convolve_over(kernel, signal)
numpy_convolve = np.convolve(signal, kernel, mode='same')

# Plot
conv_canvas, conv_panels = plt.subplots(3, 1, sharex=True, layout="constrained")

conv_panels[0].plot(signal, ".-")
conv_panels[0].set_title('Signal')

conv_panels[1].plot(kernel, ".-")
conv_panels[1].set_title('Kernel')

conv_panels[2].plot(numpy_convolve,'co', label="np.convolve")
conv_panels[2].plot(my_convolve,'b.-', label="convolve_over")
conv_panels[2].set_title('Result of convolution')
conv_panels[2].legend()
```

## Narrowband temporal filtering

```{python}

# extract data from mat file
matdata = sio.loadmat('FourierMXC_09_apps/braindata.mat')

# extract data from mat file
timevec = matdata['timevec'].flatten()
srate    = matdata['srate'].item()
braindata = matdata['braindata'].flatten()


n = len(timevec)

# plot time-domain signal
plt.plot(timevec,braindata)
plt.xlim([-.5,1.5])
plt.xlabel('Time (sec.)')
plt.ylabel(r"Voltage $\mu$V)")
plt.title('Time domain')
plt.show()
```
```{python}
# compute power spectrum
dataX    = scipy.fftpack.fft(braindata)/n
ampspect = 2*np.abs(dataX)**2
hz       = np.linspace(0,srate,n) # out to srate as trick for the filter

# plot power spectrum
plt.plot(hz,ampspect[0:len(hz)])
plt.xlim([0,100])
plt.ylim([0,500])
plt.xlabel("Frequency (Hz)")
plt.ylabel(r"Voltage ($\mu$V)")
plt.title("Frequency domain")
plt.show()
```


```{python}
# specify which frequencies to filter
peakFiltFreqs = [2,47] # Hz

c = 'kr' # line colors

# loop over frequencies
for fi in range(0,len(peakFiltFreqs)):
    
    # construct the filter
    x  = hz-peakFiltFreqs[fi] # shifted frequencies
    fx = np.exp(-(x/4)**2)    # gaussian
    
    # apply the filter to the data
    filtdat = 2*np.real( scipy.fftpack.ifft( np.multiply(dataX,fx) ))
    
    # show the results
    plt.plot(timevec,filtdat,c[fi],label='%g Hz' %peakFiltFreqs[fi])
    plt.xlim([-.5,1.5])
    plt.xlabel('Time (sec.)')
    plt.ylabel(r"Voltage ($\mu$V)")
    plt.title('Time domain')

#plt.legend()
plt.show()
```

## Image smoothing and sharpening

```{python}
# load image and convert to float
lenna = np.asarray( Image.open("FourierMXC_09_apps/Lenna.png") )
imgL  = np.mean(lenna,axis=2)

# plot original image
plt.subplot2grid((2,2),(0,0))
plt.imshow(imgL,cmap=plt.cm.gray)
plt.axis('off')
plt.title('Original image')


# and its power spectrum
imgX  = scipy.fftpack.fftshift(scipy.fftpack.fft2(imgL))
powr2 = np.log(np.abs(imgX))

plt.subplot2grid((2,3),(1,0))
plt.imshow(powr2,cmap=plt.cm.gray)
plt.clim([0,15])
plt.axis('off')
plt.title('Amplitude spectrum')


# filter kernel is a Gaussian
width = .1 # width of gaussian (normalized Z units)
lims  = np.shape(imgL)
xr    = stats.zscore(np.arange(lims[0]))
[x,y] = np.meshgrid(xr,xr)

# add 1- at beginning of the next line to invert the filter
gaus2d = np.exp( -( x**2 + y**2 ) / (2*width**2) )


# show Gaussian
plt.subplot2grid((2,3),(1,1))
plt.imshow(gaus2d,cmap=plt.cm.gray)
plt.axis('off')
plt.title('Gain function')


# show modulated spectrum
plt.subplot2grid((2,3),(1,2))
plt.imshow( np.log(np.abs( np.multiply(imgX,gaus2d)) ) ,cmap=plt.cm.gray)
plt.axis('off')
plt.clim([0,15])
plt.title('Modulated spectrum')


# and the reconstructed image
imgrecon = np.real(scipy.fftpack.ifft2( np.multiply(imgX,gaus2d) ))

plt.subplot2grid((2,2),(0,1))
plt.imshow( imgrecon ,cmap=plt.cm.gray)
plt.axis('off')
plt.title('Filtered image')

plt.show()
```

## Image narrowband filtering

```{python}

# specify vector of sine phases
sinephas = [ 0 , np.pi/4 ]

# vector of sine frequencies
sinefreq = [.1 , .05] # arbitrary units


# sine wave initializations
lims  = [-91,91]
[x,y] = np.meshgrid(range(lims[0],lims[1]),range(lims[0],lims[1]))


# compute 2D sine gradients
xp = x*np.cos(sinephas[0]) + y*np.sin(sinephas[0])
img1 = np.sin( 2*np.pi*sinefreq[0]*xp )

xp = x*np.cos(sinephas[1]) + y*np.sin(sinephas[1])
img2 = np.sin( 2*np.pi*sinefreq[1]*xp )

# combine images
img = img1+img2



# show original two gradients
plt.subplot2grid((3,2),(0,0))
plt.imshow(img1)
plt.axis('off')
plt.title('Image 1')

plt.subplot2grid((3,2),(0,1))
plt.imshow(img2)
plt.axis('off')
plt.title('Image 2')


# show sum
plt.subplot2grid((3,2),(1,0))
plt.imshow(img)
plt.axis('off')
plt.title('Combined')


# FFT
imgX    = scipy.fftpack.fft2(img)
imgXamp = np.abs(imgX)

# show amplitude spectrum
plt.subplot2grid((3,2),(1,1))
plt.imshow(scipy.fftpack.fftshift(imgXamp))
plt.axis('off')
plt.clim([0,500])
plt.title('Amplitude spectrum')

# show sum down columns
plt.subplot2grid((3,2),(2,0))
plt.stem(np.sum(imgXamp,axis=1))
plt.title('Column sum')

# replace 1st column with last
imgX[0,:] = imgX[-1,:]

# reconstructed image
imgrecon  = np.real( scipy.fftpack.ifft2(imgX) )

plt.subplot2grid((3,2),(2,1))
plt.imshow(imgrecon)
plt.title('Filtered image')

plt.show()
```